import AppKit
import Foundation
import Metal
import OSLog
import simd
import VisualizerCore

// ── SHELL RENDER PASS ───────────────────────────────────────────────────────
//
// Renders an arbitrary list of "shells" (small bright emissive cores +
// optional halos) as billboard quads through a Metal render pipeline.
// Writes DEPTH so the cloud raymarch (Phase 2) can detect "shell is in
// front of cloud → cloud should not obscure it" and "shell is behind
// cloud → cloud occludes it."
//
// This is the bridge that makes "shells rising through clouds" actually
// work — without something writing real depth, the cloud pass has nothing
// to terminate against.
//
// REUSABLE for any scene that needs a "small bright point in scene space
// with depth write" — sparkler tips, flashlights, eyes, distant lights,
// etc. Anywhere a bright pinpoint needs proper depth interaction with
// other Metal passes.

/// A renderable shell — small bright billboard with optional halo.
public struct ShellRenderItem {
    /// World position of the shell's centre.
    public var position: SIMD3<Float>
    /// Core sphere radius (m). Drawn as a billboard quad of this size,
    /// sampled through the same soft-sparkle sprite the streak quads use
    /// so the visual is consistent.
    public var coreRadius: Float
    /// Halo radius (m). Larger billboard at lower intensity surrounding
    /// the core. Set to 0 to disable.
    public var haloRadius: Float
    /// Linear HDR colour of the core (typically warm white-yellow). The
    /// shader multiplies by the sprite alpha.
    public var coreColor: SIMD3<Float>
    /// Linear HDR colour of the halo (typically same hue, dimmer).
    public var haloColor: SIMD3<Float>

    public init(
        position: SIMD3<Float>,
        coreRadius: Float = 0.04,
        haloRadius: Float = 0.13,
        coreColor: SIMD3<Float> = SIMD3(3.0, 2.6, 1.6),
        haloColor: SIMD3<Float> = SIMD3(1.2, 0.95, 0.50)
    ) {
        self.position = position
        self.coreRadius = coreRadius
        self.haloRadius = haloRadius
        self.coreColor = coreColor
        self.haloColor = haloColor
    }
}

/// Per-instance GPU vertex generated by the host each frame. 32 bytes,
/// float4-aligned per the project ALIGNMENT RULE. Six instances expand
/// to two camera-facing triangles in the vertex shader.
public struct ShellVertex {
    public var positionRadius: SIMD4<Float>  // xyz = world, w = radius
    public var color: SIMD4<Float>           // rgb = HDR colour, a = vertex corner index [0..3]
}

@MainActor
public final class ShellRenderPass {

    private static let log = Logger(subsystem: AppLog.subsystem, category: "ShellRenderPass")

    public let device: MTLDevice
    public let engine: SimEngine

    /// Maximum number of shells the renderer can handle in one frame. Each
    /// shell takes 8 vertices (4 core + 4 halo) and 12 indices (6 core + 6
    /// halo). 256 shells = 2048 vertices = 64 KB, trivial.
    public let capacity: Int

    private let pipeline: MTLRenderPipelineState
    private let depthState: MTLDepthStencilState
    private let vertexBuffer: MTLBuffer
    private let indexBuffer: MTLBuffer
    private let spriteTexture: MTLTexture

    public init?(
        engine: SimEngine,
        spriteTexture: MTLTexture,
        capacity: Int = 256
    ) {
        let device = engine.device
        self.device = device
        self.engine = engine
        self.capacity = capacity
        self.spriteTexture = spriteTexture

        // 8 verts/shell × 32 bytes/vert
        let vertexBytes = capacity * 8 * MemoryLayout<ShellVertex>.stride
        // 12 indices/shell × 4 bytes/index
        let indexBytes = capacity * 12 * MemoryLayout<UInt32>.stride
        guard
            let vBuf = device.makeBuffer(length: vertexBytes, options: .storageModeShared),
            let iBuf = device.makeBuffer(length: indexBytes, options: .storageModeShared)
        else {
            Self.log.error("ShellRenderPass buffer alloc failed")
            return nil
        }
        vBuf.label = "ShellRenderPass.vertices"
        iBuf.label = "ShellRenderPass.indices"

        // Pre-fill the index buffer — fixed pattern per shell (4 verts per
        // billboard, 2 triangles each, 6 indices per billboard, 12 per shell).
        let idxPtr = iBuf.contents().bindMemory(to: UInt32.self, capacity: capacity * 12)
        for s in 0..<capacity {
            // 4 verts/billboard, 2 billboards (core + halo) = 8 verts/shell
            let base = UInt32(s * 8)
            let dst = s * 12
            // Core billboard (verts 0..3, indices 0..5)
            idxPtr[dst + 0] = base + 0
            idxPtr[dst + 1] = base + 1
            idxPtr[dst + 2] = base + 2
            idxPtr[dst + 3] = base + 0
            idxPtr[dst + 4] = base + 2
            idxPtr[dst + 5] = base + 3
            // Halo billboard (verts 4..7, indices 6..11)
            idxPtr[dst + 6] = base + 4
            idxPtr[dst + 7] = base + 5
            idxPtr[dst + 8] = base + 6
            idxPtr[dst + 9] = base + 4
            idxPtr[dst + 10] = base + 6
            idxPtr[dst + 11] = base + 7
        }
        self.vertexBuffer = vBuf
        self.indexBuffer = iBuf

        // Vertex descriptor — interleaved positionRadius (float4) + color (float4)
        let vd = MTLVertexDescriptor()
        vd.attributes[0].format = .float4
        vd.attributes[0].offset = 0
        vd.attributes[0].bufferIndex = 0
        vd.attributes[1].format = .float4
        vd.attributes[1].offset = 16
        vd.attributes[1].bufferIndex = 0
        vd.layouts[0].stride = 32
        vd.layouts[0].stepFunction = .perVertex

        guard let library = engine.library,
              let vfn = library.makeFunction(name: "shellPassVS"),
              let ffn = library.makeFunction(name: "shellPassFS") else {
            Self.log.error("ShellRenderPass: vertex/fragment functions not found")
            return nil
        }

        let desc = MTLRenderPipelineDescriptor()
        desc.label = "ShellRenderPass"
        desc.vertexFunction = vfn
        desc.fragmentFunction = ffn
        desc.vertexDescriptor = vd
        let colorAtt = desc.colorAttachments[0]!
        colorAtt.pixelFormat = .rgba16Float
        // Additive blend — shells add their bright core into the scene.
        colorAtt.isBlendingEnabled = true
        colorAtt.rgbBlendOperation = .add
        colorAtt.alphaBlendOperation = .add
        colorAtt.sourceRGBBlendFactor = .one
        colorAtt.sourceAlphaBlendFactor = .one
        colorAtt.destinationRGBBlendFactor = .one
        colorAtt.destinationAlphaBlendFactor = .one
        desc.depthAttachmentPixelFormat = .depth32Float

        guard let pipeline = try? device.makeRenderPipelineState(descriptor: desc) else {
            Self.log.error("ShellRenderPass: pipeline build failed")
            return nil
        }
        self.pipeline = pipeline

        // Depth state: TEST + WRITE. Shells write real depth so the cloud
        // raymarch (Phase 2) terminates correctly when a ray passes through
        // the shell's screen-space pixel. The core writes depth; the halo
        // is alpha-blend-additive over it and doesn't need its own write
        // (same depth would clip ordering oddly with additive — disable
        // depth write on halo via a separate state if needed; for now the
        // single state writes both since the core writes first and the
        // halo gets the same depth value).
        let depthDesc = MTLDepthStencilDescriptor()
        depthDesc.depthCompareFunction = .lessEqual
        depthDesc.isDepthWriteEnabled = true
        guard let depthState = device.makeDepthStencilState(descriptor: depthDesc) else {
            Self.log.error("ShellRenderPass: depth state build failed")
            return nil
        }
        self.depthState = depthState
    }

    /// Build vertices for the host's current list of shells, then encode
    /// the draw against the compositor's HDR + depth target.
    public func encode(
        into cb: MTLCommandBuffer,
        target: FrameCompositor,
        viewProjection: float4x4,
        cameraRight: SIMD3<Float>,
        cameraUp: SIMD3<Float>,
        shells: [ShellRenderItem]
    ) {
        let n = min(shells.count, capacity)
        guard n > 0 else { return }

        let vptr = vertexBuffer.contents().bindMemory(to: ShellVertex.self, capacity: capacity * 8)
        for i in 0..<n {
            let s = shells[i]
            let base = i * 8
            // Core billboard, 4 corners. The vertex shader expands each
            // billboard into a screen-aligned quad using cameraRight + cameraUp.
            // We tag corner index in color.a so the VS knows which corner.
            let coreColor4 = SIMD4(s.coreColor.x, s.coreColor.y, s.coreColor.z, 0)
            let posR = SIMD4(s.position.x, s.position.y, s.position.z, s.coreRadius)
            for c in 0..<4 {
                var color = coreColor4
                color.w = Float(c)
                vptr[base + c] = ShellVertex(positionRadius: posR, color: color)
            }
            // Halo billboard
            let haloColor4 = SIMD4(s.haloColor.x, s.haloColor.y, s.haloColor.z, 0)
            let haloR = SIMD4(s.position.x, s.position.y, s.position.z, s.haloRadius)
            for c in 0..<4 {
                var color = haloColor4
                color.w = Float(c + 4)   // halo corners are tagged 4..7
                vptr[base + 4 + c] = ShellVertex(positionRadius: haloR, color: color)
            }
        }

        let pass = target.makeRenderPassDescriptor()
        guard let enc = cb.makeRenderCommandEncoder(descriptor: pass) else { return }
        enc.label = "ShellRenderPass"
        enc.setRenderPipelineState(pipeline)
        enc.setDepthStencilState(depthState)
        enc.setCullMode(.none)

        enc.setVertexBuffer(vertexBuffer, offset: 0, index: 0)
        var vp = viewProjection
        var right = SIMD4(cameraRight.x, cameraRight.y, cameraRight.z, 0)
        var up = SIMD4(cameraUp.x, cameraUp.y, cameraUp.z, 0)
        enc.setVertexBytes(&vp, length: MemoryLayout<float4x4>.size, index: 1)
        enc.setVertexBytes(&right, length: MemoryLayout<SIMD4<Float>>.size, index: 2)
        enc.setVertexBytes(&up, length: MemoryLayout<SIMD4<Float>>.size, index: 3)

        enc.setFragmentTexture(spriteTexture, index: 0)

        enc.drawIndexedPrimitives(
            type: .triangle,
            indexCount: n * 12,
            indexType: .uint32,
            indexBuffer: indexBuffer,
            indexBufferOffset: 0
        )
        enc.endEncoding()
    }
}
